development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: duncan
  password: il1ketrains

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: duncan
  password: il1ketrains


production:
  adapter: postgresql
  encoding: unicode
  database: voicey_production
  pool: 5
  username: duncan
  password: il1ketrains
